# Generated by Django 5.1.4 on 2024-12-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_account_daily_usage_account_last_usage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='daily_usage',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_usage_date',
        ),
        migrations.RemoveField(
            model_name='urlaccess',
            name='referer',
        ),
    ]
